name: 'auto publisher'
author: 'K Sai Aditya'
description: 'Update apps in Microsoft Store'
inputs:
  command:
    description: 'The command to execute. Available command: getmetadata, getmetadataandfilter, publish'
    required: true
    default: 'publish'
  interactive:
    description: 'u want pdp? true:false;'
    required: true
    default: 'false'
  product-id:
    description: 'Product Id'
    required: true
  seller-id:
    description: 'Seller Id'
    required: true
  tenant-id:
    description: 'AAD Tenant Id'
    required: true
  client-id:
    description: 'App Client Id'
    required: true
  client-secret:
    description: 'App Client secret'
    required: true
  package:
    description: 'Path to the app directory to upload for msix and product json for win32'
    required: false
  photos-path:
    description: 'Path to the photos directory to upload'
    required: false
  json-file-path:
    description: 'Path to the JSON file containing app metadata'
    required: false
  download:
    description: 'set this flag to download metadata and media files which have been changed/added in pdp'
    required: false
    default: 'false'
  type:
    description: 'packaged or win32; if not specified, defaults to packaged'
    required: true
    default: 'packaged'
  type:
    description: 'set flag true if want to append media files else media files will be replaced'
    required: true
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/main.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'