name: 'Auto Publisher'
author: 'K Sai Aditya'
description: 'Update apps in Microsoft Store'

inputs:
  seller-id:
    description: 'Seller Id'
    required: true
  product-id:
    description: 'Product Id'
    required: false
  tenant-id:
    description: 'AAD Tenant Id'
    required: true
  client-id:
    description: 'App Client Id'
    required: true
  client-secret:
    description: 'App Client secret'
    required: true
  file-type:
    description: 'Type of file to upload (msi, msix, flight)'
    required: false
    default: 'msi'
  file-path:
    description: 'Path to the file to upload'
    required: false
  flight-name:
    description: 'Name of the flight to upload (only for flight type)'
    required: false

runs:
  using: 'node12'
  main: "${{ github.action_path }}"/dist/x.js

branding:
  icon: 'upload-cloud'
  color: 'blue'
